=== geometer/FBReaderJ-alex/data/network/catalog.dtd
<!ELEMENT catalog (site,title,summary?,link+,advancedSearch?,relationAliases?,feeds?,authentication?,urlRewritingRules?,icon)>
<!ATTLIST catalog 
	type (opds) #REQUIRED
	hasStableIdentifiers (true|false) "false"
>

<!ELEMENT site (#PCDATA)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT summary (#PCDATA)>
<!ELEMENT icon (#PCDATA)>

<!ELEMENT link (#PCDATA)>
<!ATTLIST link 
	rel (main|search|signIn|signOut|signUp|refillAccount|recoverPassword) #REQUIRED
	type CDATA #REQUIRED
>

<!ELEMENT relationAliases (alias+)>
<!ELEMENT alias EMPTY>
<!ATTLIST alias
	alias CDATA #REQUIRED
	name CDATA #REQUIRED
	type CDATA ""
>

<!ELEMENT advancedSearch (field+)>
<!ATTLIST advancedSearch
	style (separateWords|quoted) #REQUIRED
>

<!ELEMENT field (#PCDATA)>
<!ATTLIST field
	name (author|titleOrSeries|tag|annotation) #REQUIRED
>

<!ELEMENT feeds (condition+)>

<!ELEMENT condition (#PCDATA)>
<!ATTLIST condition
	show (never|signedIn) #REQUIRED
>

<!ELEMENT authentication EMPTY>
<!ATTLIST authentication
	type (basic|litres) #REQUIRED
>

<!ELEMENT urlRewritingRules (rule+)>

<!ELEMENT rule EMPTY>
<!ATTLIST rule
	type (addUrlParameter) #REQUIRED
	apply (always|external|internal) "always"
	name CDATA #REQUIRED
	value CDATA #REQUIRED
>

=== geometer/FBReaderJ-alex/data/network/smashwords.com.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<catalog type="opds">
	<site>smashwords.com</site>
	<title>Smashwords</title>
	<summary>Ebooks from independent authors and publishers</summary>
	<link rel="main" type="application/atom+xml">http://smashwords.com/atom</link>
	<link rel="search" type="application/atom+xml">http://smashwords.com/atom/search/books?query=%s</link>
	<advancedSearch style="quoted">
		<field name="author">authorFullName</field>
		<field name="titleOrSeries">title</field>
		<field name="tag">categories</field>
		<field name="annotation">description</field>
	</advancedSearch>
	<relationAliases>
		<alias alias="x-stanza-cover-image-thumbnail" name="http://opds-spec.org/thumbnail" />
		<alias alias="x-stanza-cover-image" name="http://opds-spec.org/cover" />
		<alias alias="bookinfo" name="http://opds-spec.org/acquisition/buy" type="text/html" />
		<alias alias="" name="http://data.fbreader.org/acquisition/sampleOrFull" type="application/epub+zip" />
	</relationAliases>
	<urlRewritingRules>
		<rule type="addUrlParameter" apply="external" name="ref" value="geometer"/>
	</urlRewritingRules>
	<icon>data:image/png;base64,
iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAIAAADYYG7QAAAAAXNSR0IArs4c6QAAAAlwSFlzAAAL
EwAACxMBAJqcGAAAAAd0SU1FB9gLFAUcBH3DnpQAAAizSURBVFjDzVldbBPZFT73zp3x+Dcex3+Q
xCyQApuyDeW/P1poVRVoQAmiu32oEFKFqqq0TSAPFKlVxUN2KRJqeaOr7q60oKK8tGSbVKVC4oFF
2y40S7qgANU2hIQswY7tzIxnxvNzbx8GjJM4wQ5L1aMr+Xrm+Nzvnr977jFijMH/E+Eq+cpxV78H
RVEopS8EEEIIAO7du+fOn4mJUjowMLBjx45bt27VpiJWNQ0ODvr9/s7OzmqYDcNob28HgNHRUVYL
1QBIVdVIJLJ69erx8fFnMmuatn79+o6ODsdxKKXVr1KDD/n9/hMnTty5c+f8+fOO4yxgNVf0xMTE
1q1bS+b+/E3m7ru1tVWSJFmWF+bM5/OhUGhgYIDVSHgWsoXjSBTFnp6eVatWEUKe6ddtbW0tLS21
Ri4qB4EQ0jTN5/M9Zy5xRc2dz+VhjKXT6VgsVuLB5YF9+fLlnTt3njlzZj4lVZmByhHM50AIoWw2
e+jQoT179kxMTFT2oV27dgEAz/Pnzp1jjNUUHdWTKzaTybgu39XVNW/YDwwMxONxURQB4OzZs6Zp
shdDd+/ebWlpaWxs7O/vdyGWNg+zgD948KC3t3fv3r2EkJMnT74INLIsHzx48MiRI24+m2UHNMvV
XZMXCoXR0VFBEJqbmz/349OyLEVRJEmq6F5oPud1ud23bjiUP1nYkRcXjwsBqshq2/bFixez6UmE
y/M7A0AIIZ4QhBEAMECEEMJx7mue5zHHMcYwwoQQBoAQEI54/YG1a9d6vd5Z65L5YhshJMvK6dO/
tW2b47hwODw0dOO9s38Q482AEEBpG4g6FlCKn6CkjoWAIYQBgDomAoQQMMaYY7s81LE4jvNh++13
321ra3s2IFcxb7zxZv+f379+/bpl28lkMpvNih4+sHTN5p+cc4qFGZUGsBn6YqwMLit9Mva4MGLU
QQj//fT3NFWpoR46+es3P/z47vLVawkhfX19HR17+/70R1847tiWY5vlg9nW0+FYjNqMOk8GfTzY
0zINczxCCBzTW+lImBfQiuUvBVZs/HbH99esWZPNZiUpXDR0m/NiDrtaXBwBACBwLANTq1pArg8t
Wdqg5dNKQVuyJKGqajweV1UFPCH03GGPEHIsQ0COr0pA7j4am5qoJhf0YmNjk23bsVhsOp/n/ZGF
jrPHrxAAKj+U5izAOUWd5zlfTSZramoCS5NVrWFpg67ryWQyl8sLgXpWoWgvZVkAzGn5R4YyBQhj
ImDMoUobtg2V5wWvtwIgMh+gxsYmoLasFJYsaXYcJ5lI3PjnR57gMsacuXrBmHCinyPCnb+c1u9e
0gqFL3y3h/jrBG+IeLyM0hkpDWHLUHmBr6iheQE1NDSAY8tqIRqLFotmLBbL5qfFYIRRZ07+xIY8
+e++s0ZmJGg/+uTGxz8/evTtd34aDXl0ym/48TluJiaEsaVN87zgnuLVmiwej4NjqQU9GAhijOPx
2LSqC74QMDozTQMg9mlfzw+/2fSdTS8JhESjsZdbvphKhMfHx1uaU9S2MMcjhJ/WhAhb+jTP8+Kc
NL0QoPr6esQjTdc5wkmRSKQ+quqWRwwwyma6BaKmKXnZkaO/+NGhnymqqqpqS0tLLJH0iF5C+Nt/
e2v4r79ziupTqyFkFfKiIIgeTw2AJEkK+ERdL1KHSuEwUEcxKCd4ABiU1YMADBHeAj6TTq9bt44Q
ks/nk8lkLpcDANMsbllqvtqgj/3rMiDsahQBMgu5YChACKkBkCiK4VDQtMyCVli+YoWqyIaDuMe1
/QwdYUwsEGQ5Hw6HI5GIoih+v980Tdu2TdN87bXXX/nSK2bRerIBAISK6nQoVFfDVdo96iUpbJtW
NptLJhKyPG2CgDBXSQaiJKDIimvobDZbSmaO46RSqVw2xxG+TDo1tXyoLlwDIFdcIhphjpXJZAFA
UWSHE2G+pEhE3dDdUEin0+6W3DbDsmXLcvkcJ3hKZwBjrKhOh8NSzc2GRDwGzElnpgBAkWVGAgwq
tjIQAOUwdgHJslwsFt0yWRCEeDyezmR5bx1HBI4IHO9BGJuGUheurCGyAKB4Ig7sk6n8NAComg68
15QzdlED5p7h7nluA0J2IesRvQAQCoVUVTVNEyFkGIYoij6f79Hkw4x8sTgx5FgGtU3m2KBmpPpY
bYAQQtFoDKj92cNJABj5z6c2EC37gFoGAsSYwxgghCi1MccjS/eIIgBs2bJFkqRoNHr48GFCSHd3
N8Z4Kq9EX/5WKJYChBDCgPBng/11dXU1aygiSV6feP3WyPJUowKBVa+f8EdTT8Ielcda/h/vhYJB
AGhvb3fLjK6uLozxvn37KKUF3VzWvNVfnwRKMcfLD4YBIJVqqhnQqtVrID8a+HK7RVl9tDF9+4OH
psEYBcdGGGxTZ5Qxx2aOmQpyDY0pAOCelNKliSzL6Yl7uXcOYUKYYwIgM/9w06ZNO3bsrNlkX/nq
135zsmeg//30o4wnfadOCnuCHo7jxsfHP/jwo2+8+vVYMnZj6IauG7986/dhSaqYO65duwaM/urw
D8JSmOMIx3Giz7drV1v5Taaqdkzp/qaq6tTUVD6XKxRUTdMMw8hkMsFgsLu7mzE2MjIyNjY26yfl
8+3bt2/cuHEB+YvvoJULOnXqVDAYHB4erijd/Wqa5oEDBwghg4OD1XcKYNE34m3btm3YsOHmzZuz
LufuhFLa1dVVX19/9erVmvoWsOj2xcTExO7duxOJxIULF+Yuefz48Wg0eunSpVq7KPA8LRXbtjs7
OwkhbuuutPCVK1cA4NixY4uQDM/Z5mGMbd68ef/+/bN6woSQ3t7eRTSZ8PPcZkrdDM/MUmtsbMy2
bUmSFtGEWDwglzRNGxoaSiaT5Q9lWQYAVVVf4H8d89Ht27dFUQwGg+UPVVX1+XzFYnExin/Of4Ns
2x4eHvb5fCtXriw9nJycvH//fmtrqyAI/1NAFdu/1fSEF6D/AmCU/2ALMCZ7AAAAAElFTkSuQmCC
	</icon>
</catalog>

=== geometer/FBReaderJ-alex/data/network/feedbooks.com.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<catalog type="opds">
	<site>feedbooks.com</site>
	<title>Feedbooks OPDS Catalog</title>
	<summary>Feedbooks: Food for the mind. A place to discover and publish e-books.</summary>
	<link rel="main" type="application/atom+xml">http://www.feedbooks.com/catalog.atom</link>
	<link rel="search" type="application/atom+xml">http://www.feedbooks.com/books/search.atom?query=%s</link>
	<link rel="signIn" type="application/atom+xml">https://www.feedbooks.com/user/profile.atom</link>
	<link rel="signOut" type="application/atom+xml">https://www.feedbooks.com/user/signout</link>
	<advancedSearch style="separateWords">
		<field name="author">author</field>
		<field name="titleOrSeries">title</field>
		<field name="tag">type</field>
		<field name="annotation">description</field>
	</advancedSearch>
	<feeds>
		<condition show="never">http://www.feedbooks.com/news/catalog.atom</condition>
		<condition show="signedIn">https://www.feedbooks.com/user/profile.atom</condition>
	</feeds>
	<authentication type="basic"/>
	<icon>data:image/png;base64,
iVBORw0KGgoAAAANSUhEUgAAADwAAABQCAIAAADKqIEEAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9kLCwoVC/TE6x0AAA1oSURBVGje
7Vtbc1vXdV5r730uOAc3AgTAm0TaoiXarpXUrqIknqZpx26mjd2ZvrYz/QH9MXlvX/ruybQPnUzb
cR+ajmQlauTEkUTJlmTxIoEgQeJ+gHPZe68+HACCKBIUb6I9kz14IsCDb3/722vt9a0NJCL4tg0G
38LxrQQtTvXpBKA0+VITkS0YZ8gQv9GgI6U7oay0w9V6lwhyjjGdtouuaRv8GwdaEyFAN1Lrzd7d
SvtWuXmv6hFRwmBvl1IfXSq9VUyZgn2zQNe70b2tzq1y47cbzc1OAICR0gDQCqAbNiKlisnXZtL2
NwX07zeaD7a95WrnSdPf6YYNPwqV5gwREQEIoO5Hy1udRzvdgmsZHM8SdNOPVhvdx7Xe7zaaq/Xu
RifsRQoQGKDBn8mAIYQE7VC1AhkpbXB+BqCVJi9Um56/vNn+vNx8sO3t9KJIkSJCAASQWmsChjgk
FQEQEJEAX/lG1ARK01qj+/lG8/eV1kq9W+2EXqgIQSCyASCDMwQEGEm5CAyBIeArBt0J1b1q+6uq
97ju3d/urDX8UGqDoykYAgCCVNSNVNo23imlFvNu1QuurdQkEY+REhAAvbKQt9HyW4G8X+38z+Od
m+t1X2nXFIKhaXIC0ERKk9Q0nbIXLHEh53xwofDubPrW0+b11ZpSxDkiAOEg65wqaKnJl6raCf/1
bvnGWn2nFyGiZbDh/tcACGBw5hpMEX24OPnhYuG1nBMnP0WkNBCRJlJEmgDhmYROGHSsRKn1g23v
04fVLyqtbS9sBVIRcQZ8oEoiICLb5Is5989fn1wqJmfTtmvyfpZBZIiAoGNyCRGBs77S9QsHTNaX
2FFBI8JmJ7i2snNjrf5wxyu3A1swwRkfeaYmMBjmEuZUynot57gmV4pW691IaUUQx+YtL7gym1Ga
GKIiMjlr9qLPy614CxD1tUIAALQ0mUrbBiDQWOg45jz9nw+2/uXW+lfbXsYWDPfY8ZrI4qyUtKaS
tmNxpbQiGH0gAQiGjsH7+BCIKFA6UkSDWRE8A/5HU6kfnM8tZJ3xqWdfpm9XWr950mz50haM7xOi
GGKkqdwOKp0AADXswQACCMQ+QOyrQu/zpb9c2bmz2f7HqwsLE86RNA0AABxRsH4SHpNlopgv3PtB
0R4LDHv+TWp6tNP935Udx+DFpHXoIuB8JjGbtiKt670oUFoRyX1eKp7RfuuJe72Ge536S8ERGWLa
EvVeeG2l9qjWPQrT2YRxeSq92ujdr3ZCqduhhNFEdgJH+fgZFGnypbYEAwDOsB2octtv+tER4/Sb
xZRrikc73te17pOWHyflYWw5gVIPgQBqPbla7/pSD0V5YKk9DrRj8KVCci5tv1lMNYMIn+f3AKW/
RCUWZ5/NTnBttXZ9taY0AAICcMTxpBycEZOWSFqnWJUtBLLqBZ+t1gk0vpzszrga10T1Xtjw5aHW
7OwthCMcVMX4cnq7G9Z7ESBMOlbRNU8N9wmBllrf3mxdW6k9bfkGZ1Mp+6eXSucylmDsjCGPAb3j
RV+UW798XCu3fYuzgmtezLuTjpG0GJ411fuCrvvRlhd2QhVpAtC9SDV6UaT16fhQJwQ60loSGRwt
zgyGJmcvE/aPyvPhqGbjnoT940Fc1bET8eFOInqw01zGP1i9R6jGx+tOExHtXolYYKOaIgCt4wpm
91uv2hYLlX7a8sst35d6GA6VBluw6bQ1nbKdgbfbDqLblXY3UrbgBdecSyfiEvjEQOOL7O6zZdab
/s/vbHy2ulP1QjGozAJJuYTx/vzER0ul70xnAKAbqt8+bf7s+uNy2887xtW57MdLU5en0oiAp8g0
9kv80fHr9fo//99KuRX4EYnB2whgCWwF8sZaXREhwuWpzHqz918Pq16kbMGavlze6pzPNgtJ0+Sc
8JnZ9zIBUBwqcvDnD7q9SD2seQ+2uwRgcsYBNUFPKqWJMQykirTuhCrO/JGmXqQYgslZqGTDjzY7
QTuQBVcAUDuQkdYcsR1Ii7NQ0clsxBc339Omv97waWCyKCKL8zcm3YwtpKJOKFOWuDqXncskiIAh
GIzFlQMDRACliYiytninlP6LC/lIESAoRcWkOZ9NnNhGJHhWdEtFa43eWr3HEBlgbKDlEvynS8XX
JhwvVF4gXZPPZ520JeKeRvyv8SQNzjhjCGgJdnkqPekYsb3GEBMGzyeMEwOtRxZNEW16wZYXsIHR
H0eMd2cyc+lEpHSoNEe0nmuv0LBUY3FNhQAArsnfmEwOfR4CIAJFxPYpu8RL67lvR/WXFaAZRLEQ
AWmwhSg+n0SaENE1xRiNEVBcDgJAw49avtzyAi+URICIaUvkHTNti6QpxAu7/9BxWhM92vGetPyd
Xlhu+UMyEIBz7Ebq2krNNXneMV/PuQXXFHueZClmGiOlq15wY71eaQWPal6tF2oNjGHBNRdz7lIp
+U4pnXph8ofUNEGlFXxye+O/H20HSiUER4RhnDUYawbyn26uhopKrvmTi4WPl0qzmcTu4D/YFr1Q
fVnt3nzS+LflSii1gr7BhwAPqt7tSvsHnWzeNt+YdHflzkMyjXB9tf51rUtAguGL9masElPgWqt3
e7P9/nzuGeiRJGJy1o3UzaeNLyptAupJDQQw6IIRAGPQjdT11frTpv+3b01/8EbhGKAJlgruZ+ui
VZFSUcYWo21MBFBEnUCFWpsMM5awBd/b8QDQBF6oOiQJIFA6kFpr4gxtwW2DCUQN0Arkl1Xv2mpt
fsJZzLtDug/N9FIh+cHi5KRrtgNZafvllj/MA1KTa/Ifnp8QnLkG/5PZzFRqnIlICJLAFvzyVDpl
CwNRamr0ooc1rxvphGCCYUR0Z6v9H19t/cMfz2UHcfDQTBuC/Wghf2UuG0j9i/ub/35vUyoV6yLU
esa2/+47c8WkRQCuwR2DjQ/5pmCLeefvvzs7n3UYAkP8cqvzyZ3y3a32wIKizU5wc71+9Vz23ZlM
3Jg8NNMEkLJEyhIxr6OyJgLOcDpl5ZyDzQapiTNYzLl/dal4ZTY7bJNmbCEY/vzuxm+eNjkDBCSg
ZiDvVFpvF1Pxx45eBPiRCqQe3YgIoIkiTQeeCAiAiFxDLBWSV+cmRhu7tuDfP5+7kHN7UikNiGAw
pjQtb3UCpY9UudDxiruRYC8YK7jmwoRTdHfrnjGYTltTSYsz1AQIEGm95cUUnV25pTWYHEtJayZl
7znz1yfcy6W0wVFpetFcZofV9InU3xpIcMxYIrlP5WIKljA4AtJe33wMeRzDnCECBORs3y5oqLSv
9H4snQXTAIigibqR6jcAXhidUNZ7oSbaUzziDJgG4IihpG0vavT27q2s1LvLW20iEAw1PX8GOCum
BUNfqccN7+5Wu+XLXe/2IlnrhiMVFxmcTbn28MB4XE3jUSQNAMAQvVDdKjd/8eVmfYTvStv/5Hb5
1+sNgyFjSASh0ibHH87nhlaEOA7Tut+UxyP8P2dIRE+b/qcPq1LTpUnHEtwL1b1q59OH1fWmbwsG
ABqIMyy65ntzGfuIoGmP88NzBhKNry9pCBwBNEBPqsf1bnO5Mp+1LMFbgay0g+1uFLfGpSZNNJOy
vzeXLboWHt9hQsCEYLZggZTxxaQD1EJx+T2cOyEAZyg1rbd6tW7AOQuklposzgzONFF8YeC705kP
FgvGSAdCvNyaDu7DjIAyGJ7LJObSiW2vxRghoMVZ3jH26/5zRFvw+LaKVOSafCZlJwTb9IKqF0oC
pTRHNAQDhFBphlh0rbdLyQ8XJ3f198Whs8JI0npnKr3W6K3Ue4HSBDCftd+fzyX2upWJgJmEcamQ
fLDj1f2IpDqfSfz1xdJ0yrqxVvvVer0ntdQ0LMgdwyi45vfmsh+/WZpLJ44Tp3GXYvOO+eMLkwZn
96ptX6qrcxN/8+b0nlc1EGEqaX20VEKgO5tt1xTvzWavnsvmHfOtUvInF4vXVmrrzV6oSBNpoPdm
Mn+2kM+55p4UHNc1nUnaHy4WrpzLKkX5/WrvwZhIGH95sXjl3ITJWM4xUpYAgIxtJE1jImF4YV/z
BDDpmIX9O4DHBS045h0z5xgwKEzHj4JjTTrmrg9zBqO3Tw+MoifgT4+6CAcG7dEPD0cgdaUTEBER
GIIlTb6nR3NE0AdayUdIkFLTg2rnZ599HSodKppOWX+6kPvRQn7MzZoDrgONokAA5zh3cfcZgVLL
1c5X216odKh0y4/mMva7M5kiWEdhmgbyYoiB0r/baPWL2ZMbRFDrRZ+XG7bBLcEipRnDli+7kTqK
poeIEYAj+FL/aq1+80njxJmOb0b2EwBifJ1sfJdVjI/KNIhBAOArLSM68d/FMETBMN52kdJ2wphK
WWlbHAW0Y3DX4AioNMW+rMHQYKfRsx1sIQKpyBZ8OmWnrSOZ6kXXuJBz7mfsQCkAUOp0+7UEYAuW
d4zz2cSBrbp9Qacs4+q5CU1084mxUu/udCXD0yplYj7OZ+zFSff757Jvl1ImZ2OPE/trVBGFSvuR
rnrh41p32CPcfWds3DTwIEUMD+J0cTKZtQ1TMOOg3/Dgy2wsqakbKnw5SwkPSfAw9iVN8ZKWFf7h
V3KvaPw/AMARafW5GgkAAAAASUVORK5CYII=
	</icon>
</catalog>

=== geometer/FBReaderJ-alex/data/network/litres.ru.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<catalog type="opds">
	<site>litres.ru</site>
	<title>Каталог LitRes</title>
	<summary>Продажа электронных книг.</summary>
	<link rel="main" type="application/atom+xml">http://data.fbreader.org/catalogs/litres/index.php</link>
	<link rel="search" type="application/atom+xml">http://data.fbreader.org/catalogs/litres/search.php?query=%s</link>
	<link rel="signIn" type="text/html">https://robot.litres.ru/pages/catalit_authorise/?skip_ip=1&amp;lfrom=51</link>
	<link rel="signUp" type="text/html">https://robot.litres.ru/pages/catalit_register_user/?lfrom=51</link>
	<link rel="refillAccount" type="text/html">https://www.litres.ru/pages/put_money_on_account/?lfrom=51</link>
	<link rel="recoverPassword" type="text/html">http://robot.litres.ru/pages/catalit_recover_pass/?lfrom=51</link>
	<advancedSearch style="separateWords">
		<field name="author">author</field>
		<field name="titleOrSeries">titleOrSeries</field>
		<field name="tag">tag</field>
		<field name="annotation">annotation</field>
	</advancedSearch>
	<feeds>
		<condition show="signedIn">http://data.fbreader.org/catalogs/litres/my.php</condition>
	</feeds>
	<authentication type="litres"/>
	<urlRewritingRules>
		<rule type="addUrlParameter" apply="external" name="lfrom" value="51"/>
	</urlRewritingRules>
	<icon>data:image/png;base64,
iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAIAAABMXPacAAAABGdBTUEAAK/I
NwWK6QAAABl0RVh0U29mdHdhcmUAQWRvYmUgSW1hZ2VSZWFkeXHJZTwAAAyk
SURBVHja7F1NbBvHFZ5ZyZJQ2CTTwHGi0BaL/NimFFEtksZObEvKIQVyKGQ0
B6MJENuHnorCTgr0FKXurahR+FD0UKC120MRoEYjtMih6cGSHbeMi8KSnNCS
fwLaImw1kmuKYozUkrh9O8Md7pJLcmd3Z//IZ2W5XJER+b5573vvzcxbLMsy
EiZyfhat3kTrRd3VjS+Vi1WvLH5eftnmp6QXfo1aRjrF/u8XPpCX/8H3luJN
gA3HBlsEAEns/377QSvvuvv31rEAsQAoA7lnG7fjWvyo2mu1AbCOwTfetEIe
Cx+0CADYMgnn8/kjR47AcWhoKBqNxmIxOIHrCSLaV5YufI97RPdsk/b+oQ1A
XZmcnDx48CBov8FrAI8YkbeGO76bWuX+ZLvfwY+/2gbAQI4fP37q1Cnzr49t
7rz3l1cs8Af+5i/aAOgkm83CwJ+enqZPR0ZH33jjzWKxeG1+HmM8Nz+3urqK
Ebp06VLVG3/3k4G3vtPL++He/mP3zI1V6uKUPzcyYujiWgWAiYkJ6vThfMuW
LePv/XR09BUswT8QSSIPmhMMwMzNzWGMrl69urWn8MO9V3k/3O//dufozz9t
7OLgZHh4WAsMux4qALRuZ/+BA++++14kElF0TfQtGQBQQYI8wY8v/rLnq2t8
PF9cf+r75+Fo7bsxi+nr69MCQ68HCYAzZ87A2KfnTz/zzP79B3p7e5/o7QUN
P7tzp4IElvSmIOEyNJVL3Wu5R+//SUm+1+/Bj8nP96/73/r34o6FhdtwfuXK
lZWVwspKHk7sf3OtxXjo4kwBADHP6OhoE3pAaO3554EA5C2R0q5dCFzPk0/K
8TioXn7xRa0pUHhAwCDgVQoea/cQRl0P5uDzdKwtdawtV0LYrq2ryV/Bb5U3
IMxO4L/bROD0yuzsCpHZ2Vl4yy0i9lXjjotzEoAmEonIu3crSVYyiSNRRZV7
9yqqjEbxQH/FW6Hyo4IHRgDG+uak3P1YBQIVAMROKk91x/PnL8BDPg/AzGiB
mZqackR3jrg4xwD4GKG4zbHQ348iUUWpL72k6DMakwYGQJMdzz2ngISrAGD2
UAcJHSDqA3tEGFzZzIwCDBzBeujXhCOcszDPjgAYp0+fHhsbcwmA9xHaI9hd
drz8MihQikYBEuXp4CCcw5VN+/fXAED/Vam/GgWGhu5UfQIwaIGBEJwaEFxv
nIEyOXfuXFNr6ETBkY2LF5UjkM2HHxoMpWi0c1ApYsNRIq6g68ABpdoVi21K
pWRFq8pgU5SrfSxrW71EK1HkOq2sMA6oxakeMPS6w2Go7i97ZAE2BWDAJNrp
Jgq925dYTPRFEEqlhjoeiTUwBfOqWF9fv3Hz8927dobTAmzKGvH4IA/Pn1fi
K4R+hFBG/W0Soa3Dw4DHYCLR0Zfox+jRVAr8OFzv0StRYzc6WV6+N3/t+pcP
HnB9qhYCoDooQ+gkQocQKpCnGRIeweGvRjESwPD1RAJ+ksSSBmIxePtjIyMU
Hhj489dvLC0tbWyUvvjiP0Iy4RC4IEMBvb9m4+3wlf98d/H27YWHa2ul0gb8
u3z58jtvH9PYShNxbEKmEEw7SBI7sCOg/VKpRLNMmmdyvd0sAE2z80xgfdHr
CB2zk76Uda9JJT0BINByjMBgJTLu7WW6l8owICEAhF7GiTvildITvbjGBLwE
ILiOKELiCN5qSoRWRaQKBqyMwfI4VwEoBJaNKQa/IUfz0q9ygMYOKrUgb1xQ
cI3AUlCEqwQhMS5IUw9pMoiCLq9yYiDhahbwhgPS6ggKgbxuPigiHCBpZ5s4
/5bzLigdCgxOElNoHoa+8G2EdMO/WCx6zAGhkZMmDBpXk4B07Xp54UEqlWoD
IDwoSmJcy8IeZ8K5EGEQJ8lBAwyiNWGQqCioNQGgYcV4MxLWAdAuRYgIisYb
6R/Z8EBOh6HI9toIf8rReoFpNFJlAXfv3KG/Mbk4xXkLyIXUDgyDInl3EuuX
NN1RAWi7IOfl/RoMbAdBpgHw1YJWDwPTk/qgaK9BFOQDEs6EF4MksYMqE9Ca
gi8AKITaDrQVU4zrWoA38wGtE5geNUoD5ufn2GtM1oKcXBeUUTkq1wIYjFND
7+/XLgxeXeXei8hhAU2TYep59rQGADQwJWsddTTgJQAtKGo1FFnl4DYH2EUA
qyviMaUE3sEqZG1oupX0rztifwCAWgsAmR0vffJJ2wW5mRlHKuyLrNSi+QBo
ujAiV3MS7twYDwxgFvtYmw1w1gVRvceNAEibXjDBdkM8nJ4umduK5WEIpG5w
Kj9YsADnOSBeJ303KdvOnau9CEg81OxchHOZbJ8z/JWbsFHSlRkMKgIml1EJ
JOGC1UVaoD6pJomHK9p9Qj3mSrNabO4fP/7Qic2nNUaAyzDIMui/UCh4bwHM
6e+pcVBmJstATT0Olb61sEmC2neUw3+ZGkHmKjfZuZcJh7E+UaZdG4kwjwW4
U4oQ5MFF+B9px3ZQvUz3gCOLnd+czAMKTsSdbDOp/3HF23eoKUB5Xz77lcnJ
AIcByNQBI6ypAF2FpepftyrLfDsV50k4acI+XJaveHoHcEdBxPtQF5TLLXhf
iojYo1xxyhJDwhoTQHhhgRsADgvgWhiRM5GdBd8HEROwx8IuVUPjntao/+dQ
hyZD/VO3LyMZW4oYfVeOFhEvCpLOfftY4IN1+vcIAC3NWh7vPi/A1cRBDAHF
CDx2QRm/ZsKiiJ0wL9P6Z59+JjwRM5lfROwBsJ7NBoWD1XlI5aewUhAOgMn8
Imkv83IcAFFuDWOWjqHKfLDXeYD5zMu11EwQsbNEuDwfqfIBV7zu6pxwxhxn
BIWHpb4+tTdjJR71tQWYHPLO1uPEwdmxo09Nga0jIIQDDAd4bUMzd1IzcYkF
rhQhlONF0lVTbBiaSqUmJiYavCDtROe44pkzNHDsGhpiM1k4Gu3SxGCdiUSn
90slaRGC1OIszci7nQmbhAeiIBoImY/ftbOYgFmX6XK83TyAVCHKESlnsC4Q
gLi9MNR+qvWgoZk6qH9V+bocmDbD9x6AggmDCLYwD4QQsuaAXHZBYapRdw4O
lvWvNpxecSET5vJuuVADgCE6UGtxNAezdl8PPgvgCkPDvU9GMwevTsmoz7mW
j3jZNTEdAhRqF0R4C0ChITNnQmcFquqtluJE14LSegAKYdM/QsjyxgCRpYg9
KPyCqSo0NEzv4eSjKCjcNLBpcJDdmoZ6oBV1xTxXqCLWBWVCSLwVG6hoX5+I
cQ1TsQCEuWkEm5BEusl5j0k4xH1SjPRfMQWXSJh3yDedk0kHHQPNPclcAoDL
wWUaXglBo2l2X74L5M5MbgBghuJNajbQjaY3pVJId0M+bC1QFELCydCp20Bx
sZjW9/DeNsCDTDhi5JSCPyWAkT4G9VcpIuyBqe62rb7ggBZp1YRqnM/KSt4l
ABp3Zc+1HCRlF8QKQbx7SYW7oFxDp58O+PivYmAQendt/3JAaKRH6QaB7aRg
YgFItgAGGNsLgIQCEKnvZEIWCNk0ArGlCENIwpQKMCOgdzV3IxFr+gcKreGU
NJ05lBMGgPelCJObAEIBCbbNweKjoAZNIyKBpQS6MFtjA8EpRdRqPIhzOB2V
YN9GFUIQB1RRbrhb2dv0PwKjoGSQB7jpCkTlfEbdVuWL+YDGkg5+WsBa1jMj
yKs70fw1H2AhagqEZOqGpD4g4bSJK8EVsNfXEPrItt69sYBkwGk5Q7QPx+5K
X1bsAQA2qxGZYHIAjPpDNdX1Khuw0FjSyhYlXp7JBZ8DTpEfJvq9PXhqatJV
AMxI3DQA/nf6P0PobP1vZ5MI3ADA0CbiQdgjViBuR6iNSu58DUOnFPc3DYDe
95nTvtthaGMOSPN7eR/SwFky9uuNjHqtwGP8LcKtAGDydvXBFeDbHze0y66h
Ie2oZ2mwBc2I4gB208u0xtXENVbiz21MhpTbwPfQJgXTNhqyiAIgoqpYq+iT
6m0wWVx0zMatHjyk3D1q/CPLdv+oFQAOHz48MjIySfpj3Lp1K0s6m0zydCaM
awDwD+UeshIOYIRktwFIEDHsjAZgLE9PR6en12ZmSvl81Q1efCtnieexEIzZ
NwKHXRDFBo2NVV2n99ZhePgKnqoslx8DzEjYQpHGpW4prIPS12qwqQcPa9vk
G8o1+DrgeE+cOMHcr4Uw1Be9oxvDQ5sxMTxoJ2778EAg8AOrKQjNA8DfgurZ
Hauylj4Plu0TuadiDR6rlFuOIBacU1rgAbAAz3+z2aPkacYSBhCD/rMNgIPw
AB6zBI8pAg+cw5VCfe/UBsBVeD4m1gNgLE1NFQg8z2azv3VOaf8XYACbumOQ
Xqkv2QAAAABJRU5ErkJggg==
	</icon>
</catalog>

=== geometer/FBReaderJ-alex/data/network/manybooks.net.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog SYSTEM "catalog.dtd">
<catalog type="opds">
	<site>manybooks.net</site>
	<title>ManyBooks Catalog</title>
	<summary>ManyBooks.net: The best ebooks at the best price: free!</summary>
	<link rel="main" type="application/atom+xml">http://manybooks.net/opds/</link>
	<link rel="search" type="application/atom+xml">http://manybooks.net/opds/search.php?q=%s</link>
	<relationAliases>
		<alias alias="http://opds-spec.org/opds-cover-image-thumbnail" name="http://opds-spec.org/thumbnail" />
	</relationAliases>
	<icon>data:image/png;base64,
iVBORw0KGgoAAAANSUhEUgAAAEYAAABGCAIAAAD+THXTAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJ
bWFnZVJlYWR5ccllPAAAA+pJREFUeNrsmz1sEzEUxx3UrUh0KiNJ56KGCTaCwggFxrAkEjA3c4vU
MABrYC1DJsJGWtYiXTbYgpKZhLFMQSJz+Tvv8s65fJAPx2dHZ52iRnm688/v/57f2W7i8oFYs3ZF
iBgpRoqRYiRLkTavrQsSSLJ5cfRZfOrqvfFGBDAgufNYXmh/u9pvbxDp9iOf5OqWuOiI07L4WpFf
n5ZcQwqRAANX+4f/K/kKLbUnsgVxMyMObtmKRF1Ej68npbq+1SRJqx42207Kzw9taWapl0ZJTmri
+2k4MZDfyEVwXdOTZr2ueOtZg7R9Q5LgosE+r4whgQ0YYLOTll9/NvxwYhHu3vUHBfLDBeOHiQX6
kliqEg/1Ej6hq/cnsEFHySFEC4eQze9fQ/chBg4tuA725pDklFKYRgKD3UyQFaDAljfehhxC9wEG
DMAM41RaihBIZAaD6qvVIGE4X5T9sYRyIBt1vEODzV1UFQhd4VcioXmJaGHG96Ehw4PwCKJFm9lj
cyJBRRg8hEq1FPSA1K8GCTmEg4T0CRuMN5zG8sOnakMGuAndh2ib/YQBvJmRFkoP9wui3ZBOIJ9Q
kFCaZqdhpGlGgg0ZkFdVp8mkkvflRzaU/c76/gmljZVnPAwbDSQYql4QJHj8fnEoPNBF1QAu3T+Q
oRLCqHpD2osyiUu3dPyJn8s2CIYcQiPNlQELj8QJV2vC0IeE/r2s+X+jlx9L/XxV990FBtRvKgZx
AljN8paWrRBPuSA2t3wMymaUBoxgrAAJUfG+EWCo7jLetNZ4kNbSdbRlb7U9Te9ziMM5E7fFyym5
Y/HlUs7mHI1uI8EzOt5wrUFCtXFUc2SFSNYTB3K2nd6KFX/6sn3tAYFBDSXFYSYo28auTzi2jgcP
vPHG+wqSg4t4GnApliZRseTolcSx9DBKxZKDMlFSuSQ8XlVVqfC+xJIDj6Yi0BQSesxxwlSq5ELL
SQ4g9foZT6VCmcvLD5okZzyWoCuVSnWg1vcOs+lhlEqr5CIqiFQq3ZKLrsYjKvhHt+SMFERTqF4/
ceEV0I4WI8VIMdKgXXTkCq5jGW9So83p5ZaULUPSsT6+hrG0YSIw5PZEZ12QniW177VELTzjPHEs
mW+8Re82UmpP7vOG9qTPK64h8SEbdRd00T3pOZFadXFSFLmShvXrsRg6dkHn99LZO/nUYiU4NzJ7
oz1pPpoiVrInvcSxqNxxeDsIPTu893+Mpudfq9nMXe6kF7oLd/HpQELi8047aWMY+pDEYN+B17VR
+IROAEFaZrfWE3r+MyabF8/7R3BaA29M2kpyBommxSjKn1UixS/qMVKMFCPZ3v4JMAC5KATHe24p
XQAAAABJRU5ErkJggg==
	</icon>
</catalog>
